### PR TITLE
add --method arg to control verb used in schema request

### PR DESCRIPTION
**Pull request by leemhenson**
Hi. A little tweak to support obtaining the schema.json via a different verb (e.g `GET`) rather rather than the currently-enforced `POST`.

### CODE REVIEW

**Comment by ThisIsMissEm** [comment]
@leemhenson is there a reason why your graphql server doesn't support POST requests? (it's pretty much a standard to use POST over GET, unless you're using some form of  persisted  queries)

**Comment by leemhenson** [comment]
No reason, I just see "give me the schema" as a GET. Insert all usual fluff about GET vs POST here.

**Comment by ThisIsMissEm** [comment]
Ah, so not supporting GET doesn't actually mean you can't use this tool?

**Comment by leemhenson** [comment]
Well, it does unless I change my server from it's, in my opinion, currently "sane" config of serving the schema over `GET`.

**Pull request closed without merging**
